name: Chrome Release Notification

on: 
  release:
    types: 
      - published

  workflow_dispatch:

jobs:

  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Notify new chrome version stable release
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: New Chrome version released! 🛑 😼 💪 ⚡
          SLACK_MESSAGE: ${{ github.event.release.tag_name }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_PERSONAL_WEBHOOK }}
          SLACK_FOOTER: ${{ github.event.release.html_url }}
